name: Test and Build
on: [push, workflow_dispatch]
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
  build:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: build project
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy project
        run: echo "Deploying to production environment"