name: Test and Build
on: [push, workflow_dispatch]
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: |
          npm cache clean -f
          rm -rf node_modules
          npm install
  test:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: |
          npm cache clean -f
          rm -rf node_modules
          npm install
      - name: run tests
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: test
    - name: get code
      uses: actions/checkout@v3
    - name: install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install dependencies
      run: |
        npm cache clean -f
        rm -rf node_modules
        npm install
    - name: run lint
      run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: |
          npm cache clean -f
          rm -rf node_modules
          npm install
      - name: build project
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: |
          npm cache clean -f
          rm -rf node_modules
          npm install
      - name: deploy project
        run: echo "Deploying to production environment"
        